### ISSUE TITLE
Android build crashes after 2.6.0

### ISSUE THREAD

**Issue by lithin** [hieuvp/react-native-fingerprint-scanner#86]
After upgrading to 2.6.0, we can't compile the app anymore. I was worried it might be due to my additions and tried locally to remove it - but the build is still broken :(

This is the trace:

```
> Task :react-native-fingerprint-scanner:compileDebugJavaWithJavac FAILED
/Users/annadoubkova/Workspace/hive-soaring-sparrow/node_modules/react-native-fingerprint-scanner/android/src/main/java/com/hieuvp/fingerprint/ReactNativeFingerprintScannerModule.java:10: error: cannot find symbol
import com.wei.android.lib.fingerprintidentify.base.BaseFingerprint.FingerprintIdentifyExceptionListener;
                                                                   ^
  symbol:   class FingerprintIdentifyExceptionListener
  location: class BaseFingerprint
/Users/annadoubkova/Workspace/hive-soaring-sparrow/node_modules/react-native-fingerprint-scanner/android/src/main/java/com/hieuvp/fingerprint/ReactNativeFingerprintScannerModule.java:11: error: cannot find symbol
import com.wei.android.lib.fingerprintidentify.base.BaseFingerprint.FingerprintIdentifyListener;
                                                                   ^
  symbol:   class FingerprintIdentifyListener
  location: class BaseFingerprint
/Users/annadoubkova/Workspace/hive-soaring-sparrow/node_modules/react-native-fingerprint-scanner/android/src/main/java/com/hieuvp/fingerprint/ReactNativeFingerprintScannerModule.java:49: error: cannot find symbol
                new FingerprintIdentifyExceptionListener() {
                    ^
  symbol:   class FingerprintIdentifyExceptionListener
  location: class ReactNativeFingerprintScannerModule
/Users/annadoubkova/Workspace/hive-soaring-sparrow/node_modules/react-native-fingerprint-scanner/android/src/main/java/com/hieuvp/fingerprint/ReactNativeFingerprintScannerModule.java:80: error: cannot find symbol
        getFingerprintIdentify().startIdentify(MAX_AVAILABLE_TIMES, new FingerprintIdentifyListener() {
                                                                        ^
  symbol:   class FingerprintIdentifyListener
  location: class ReactNativeFingerprintScannerModule
4 errors
```

Android Studio claims it can't now find 
```
import com.wei.android.lib.fingerprintidentify.base.BaseFingerprint.FingerprintIdentifyExceptionListener;
import com.wei.android.lib.fingerprintidentify.base.BaseFingerprint.FingerprintIdentifyListener;
```

I realise these have been there for 2 years but have there been any changes shipped in 2.6.0 that could've broken this?

**Comment by phillbaker** [comment]
2.6.0 also included:
* a version bump of that library
* safeExtGet to pull in the library version (#78)

Can you try specifying the previous library version (1.2.1) as a project
property in your gradle file?

Might be related to #85

**Comment by phillbaker** [comment]
It looks like this can be worked around by adding `fingerprintidentify=1.2.1` to `android/gradle.properties`.

However, I did some research and 1.2.6 is not compatible unless you're using androidx - this isn't very clear from the version number or the changelog (it's a break change seems like). I'm going to revert the change and release a new version. Sorry for the hassle.

**Comment by lithin** [comment]
Thanks @phillbaker, I'll wait for the next release :)

**Comment by phillbaker** [comment]
Fixed in https://github.com/hieuvp/react-native-fingerprint-scanner/commit/fae021cec86f47257b36e7d46a811bfa8ccff721

**Comment by praveens96** [comment]
getting 
ReactNativeFingerprintScannerModule.java:11: error: cannot find symbol
import com.wei.android.lib.fingerprintidentify.base.BaseFingerprint.FingerprintIdentifyExceptionListener;

**Comment by matheusleite** [comment]
@praveens96 get the same error here 
`cannot find symbol class FingerprintIdentifyExceptionListener`

**Comment by Usman-02501** [comment]
Could not determine the dependencies of task ':react-native-fingerprint-scanner:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-fingerprint-scanner:debugCompileClasspath'.
   > Could not find com.wei.android.lib:fingerprintidentify:1.2.6.
     Required by:
         project :react-native-fingerprint-scanner

How to solve this error in android studio (React Native)
